In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('Advertising[1].csv')

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.tail()

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [5]:
pf = ProfileReport(df)

In [6]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
pf.to_file('Test.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
x = df[["TV"]]

In [9]:
y = df.Sales

In [10]:
#start building the model
from sklearn.linear_model import LinearRegression 

In [11]:
Linear = LinearRegression()

In [12]:
Linear.fit(x,y)

LinearRegression()

In [13]:
Linear.intercept_  #value of C

7.032593549127693

In [14]:
Linear.coef_       #Value of m 

array([0.04753664])

In [15]:
file = 'linear_reg.sav'
pickle.dump(Linear , open(file,'wb'))

In [16]:
##Making Predictions
Linear.predict([[45]])

C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.17174237])

In [17]:
l = [4,5,6,89,43,56,21]


In [18]:
for i in l:
    print(Linear.predict([[i]]))

[7.22274011]
[7.27027675]
[7.31781339]
[11.26335455]
[9.07666909]
[9.69464541]
[8.030863]


C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\ANKIT\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not ha

In [19]:
L = LinearRegression()

In [21]:
data_x = df[['TV' ,'Radio','Newspaper']]

In [25]:
y = df['Sales']

In [26]:
L.fit(data_x,y)

LinearRegression()

In [27]:
L.intercept_

2.9388893694594085

In [28]:
L.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [29]:
L.score(data_x,y)

0.8972106381789522

In [31]:
import statsmodels.formula.api as smf
lm = smf.ols(formula = 'Sales ~ TV' ,data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Fri, 11 Aug 2023   Prob (F-statistic):           1.47e-42
Time:                        18:55:52   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.0326      0.458     15.360      0.000       6.130       7.935
TV             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""